### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by ghostsquad** [jsonnet-libs/xtd#1]
It seems I cannot use this library, since `main.libsonnet` imports `doc-util/main.libsonnet`

And I'm not sure where that comes from. There's also no jsonnet bundler file.

**Comment by sh0rez** [comment]
This is `doc-util` from https://github.com/sh0rez/docsonnet/tree/master/doc-util, a library that is statically compiled into that tool.

While it is not provided in the bundle here, I hope this isn't an issue, because if you only access the actual functions and not the "#" keys, there is no reference to the local after all and no attempt to import it.

Right? Otherwise please provide your code and the error message so we can debug that

**Comment by ghostsquad** [comment]
So technically you can't import from URLs like in the readme:

```
jsonnet ~/tmp/test1.jsonnet
RUNTIME ERROR: couldn't open import "github.com/jsonnet-libs/xtd/main.libsonnet": no match locally or in the Jsonnet library paths
	/Users/wmcnamee/tmp/test1.jsonnet:1:13-64	thunk <xtd> from <$>
	/Users/wmcnamee/tmp/test1.jsonnet:4:6-9
	During manifestation
```

But otherwise, if I clone the repo and use `./xtd` or use jsonnet bundler it works fine.

**Comment by sh0rez** [comment]
Ah right, that's actually a different error here. 

Try the following:

```bash
$ jb init
$ jb install github.com/jsonnet-libs/xtd
```

And then assuming your file is called `test.jsonnet`:

```bash
$ jsonnet -J vendor test.jsonnet
```

The `-J vendor` is imported, because it tells the `file.Importer` to also look at those that `jb` installed

**Comment by ghostsquad** [comment]
Oh I see

**Comment by sh0rez** [comment]
Did that work? If so, feel free to close :)

**Comment by ghostsquad** [comment]
oh, latest version of jsonnet bundler added support for symlinks! sweet. This is new.
